### PR TITLE
Cleanup a11y and TS warnings/errors

### PR DESCRIPTION
**Pull request by techniq**
`pnpm check --no-tsconfig --ignore "dist,src/routes"`

Before | After
--- | ---
image | image

```pnpm check```
Before | After
--- | ---
image | image

### CODE REVIEW

**Comment by techniq** [comment]
Focusing on lib-only initially (ignoring doc routes)

`pnpm check --no-tsconfig --ignore "dist,src/routes"`

Before | After
--- | ---
image | image

But still making progress overall

```pnpm check```
Before | After
--- | ---
image | image

**Comment by techniq** [comment]
and then there was 1...

image

**Comment by techniq** [comment]
zoolander-will-ferrell

image

image

**Comment by ttytm** [comment]
Thanks for the work 🙏

**Pull request merged**
