### PR TITLE
make DateField format and mask reactive to locale changes

### PR DESCRIPTION
**Pull request by dimfeld**

### CODE REVIEW

**Comment by techniq** [comment]
Hmm... this doesn't look to fully solve the issue.  Maybe a responsive issue in `Input` with regards to `mask`

https://github.com/techniq/svelte-ux/assets/177476/d8e411d0-c14b-40aa-87db-69cc109282d2

**Comment by dimfeld** [comment]
Maybe here? Placeholder default value is not reactive to changes in mask

https://github.com/techniq/svelte-ux/blob/ca8bdfde1307b8473ff25029e66f19314f61051e/packages/svelte-ux/src/lib/components/Input.svelte#L27

**Comment by dimfeld** [comment]
seems better now

**Comment by techniq** [comment]
Much better, thanks!

**Pull request merged**
